config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :blogs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  mount_uploader :title, ImageUploader
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }

  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blogs_path, notice: 'ブログを作成しました！'
    else
      render :new
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: 'ブログを編集しました！'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: 'ブログを削除しました！'
  end

  def confirm
    @blog = Blog.new(blog_params)

  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :title_cache)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <!-- 確認画面でアップロードした画像を表示させるための記述 -->
  <%= image_tag(@blog.title.url) if @blog.title && @blog.title.url %>
  <%= form.hidden_field :title_cache %>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@blog, url:new_blog_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :title_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/blogs/edit.html.erb
<header>
  <%= image_tag 'Facebook_Logo_Primary.png', class: 'logo' %>
</header>
<div class="container show">
  <h1>投稿編集</h1>
  <div class="row">
    <div class="col-lg-12 img_box">
      <%= form_with(model: @blog, local: true) do |form| %>
      <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= @blog.errors.count %>件のエラーがあります。
        </h2>
        <ul>
          <% @blog.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="blog_title">
        <%= form.label :画像 %>
        <%= form.file_field :title %>
      </div>
      <div class="blog_content">
        <%= form.label :テキスト %>
        <%= form.text_field :content %>
      </div>
      <%= form.submit %>
      <% end %>
    </div>
    <p class="out_txt">
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    </p>
  </div>
</div>
<p class="back">
  <%= link_to 'Back', blogs_path %>
</p>

app/views/blogs/index.html.erb
<header>
  <%= image_tag 'Facebook_Logo_Primary.png', class: 'logo' %>
</header>
<div class="container show">
  <div class="row">
    <div class="col-lg-12">
      <p class="txt">
        <%= link_to 'ストーリーズを作成', new_blog_path %>
        <span>写真、メッセージを共有しよう。</span>
      </p>
    </div>
    <% @blogs.each do |blog| %>
    <div class="col-lg-12 img_box">
      <p class="name">名前:
        <%= blog.user.name%>
      </p>
      <p class="img">
        <%= image_tag blog.title.url %>
      </p>
      <p class="content">
        <%= blog.content %>
      </p>
      <p class="link_txt">
        <span>
          <%= link_to '投稿の詳細', blog_path(blog.id) %>
        </span>
        <span>
          <%= link_to "投稿を編集", edit_blog_path(blog.id), data: { confirm: '本当に編集していいですか？' } %>
        </span>
        <span>
          <%= link_to '投稿を削除', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
        </span>
      </p>
    </div>
    <% end %>
    <p class="out_txt">
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    </p>
  </div>
</div>

app/views/blogs/new.html.erb
<header>
  <%= image_tag 'Facebook_Logo_Primary.png', class: 'logo' %>
</header>
<div class="container show">
  <h1>新規投稿</h1>
  <div class="row">
    <div class="col-lg-12 img_box">
      <%= form_with(model: @blog, local: true) do |form| %>
      <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= @blog.errors.count %>件のエラーがあります。
        </h2>
        <ul>
          <% @blog.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="blog_title">
        <%= form.label :画像 %>
        <!-- 確認画面から新規作成画面に戻った時に、 -->
        <!-- アップロードした画像を表示させるための記述 -->
        <%= image_tag(@blog.title.url) if @blog.title && @blog.title.url %>
        <%= form.file_field :title %>
        <%= form.hidden_field :image_cache %>
      </div>
      <div class="blog_content">
        <%= form.label :テキスト %>
        <%= form.text_field :content %>
      </div>
      <%= form.submit %>
      <% end %>
    </div>
    <p class="out_txt">
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    </p>
  </div>
</div>
<p class="back">
  <%= link_to 'Back', blogs_path %>
</p>

app/views/blogs/show.html.erb
<header>
  <%= image_tag 'Facebook_Logo_Primary.png', class: 'logo' %>
</header>
<div class="container show">
  <h1>投稿詳細</h1>
  <div class="row">
    <div class="col-lg-12 img_box">
      <p class="name">名前:
        <%= @blog.user.name%>
      </p>
      <p class="img">
        <%= image_tag @blog.title.url %>
      </p>
      <p class="content">
        <%= @blog.content %>
      </p>
      
    </div>
    <p class="out_txt">
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    </p>
  </div>
</div>

<p class="back"><%= link_to 'Back', blogs_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionLogin04</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="container entry">
  <div class="row">
    <div class="col-lg-12">
      <h1>アカウント登録</h1>
      <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@user.errors.count, "error") %>prohibited this 
          <%= @user.name %>from being saved:
        </h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
        </ul>
      </div>
      <% end %>
      
      <%= form_with(model: @user, local: true) do |f| %>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :email %>
        <%= f.email_field :email %>
      </p>
      <p>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </p>
      <p>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </p>
      <p>
        <%= f.submit "アカウント登録" %>
      </p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<header>
<%= image_tag 'Facebook_Logo_Primary.png', class: 'logo' %>
</header>

<div class="container show">
  <div class="row">
      <div class="col-lg-12">
          <h1><%= @user.name %>さん、Facebookへようこそ</h1>
          <!--<p>メールアドレス: <%= @user.email %></p>-->
          <p class="txt"><%= link_to '投稿一覧へ', '/blogs/' %></p>
      </div>
      <p class="out_txt"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></p>
  </div>
</div>